include:
  - template: Code-Quality.gitlab-ci.yml
code_quality:
  allow_failure: true
  artifacts:
    paths: [gl-code-quality-report.json]
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
stages:
  - build
  - test
  - deploy


test_coverage:
  allow_failure: true
  stage:
    test
  script:
    - echo $JAVA_HOME
    - chmod +x mvnw && ./mvnw clean install
    - cat target/site/jacoco/index.html


build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker version
    - docker info
    - docker rm -vf $(docker ps -aq) &&
      docker rmi -f $(docker images -aq) &&
      docker volume prune -f
    - docker-compose down --rmi all -v --remove-orphans
    - docker image ls
    - docker-compose up --no-start --force-recreate
    - docker images
  only:
    - master


deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker images
    - echo "$DOCKER_USER $DOCKER_PASSWD $IMAGE_NAME"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker tag $IMAGE_NAME:latest $DOCKER_USER/$IMAGE_NAME:latest
    - docker push $DOCKER_USER/$IMAGE_NAME:latest
  only:
    - master
