stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  script:
    - docker version
    - docker info
    - docker-compose up --no-start --force-recreate
  only:
    - master


deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  script:
    - docker images
    - echo "$DOCKER_USER $DOCKER_PASSWD"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker tag postgres:11.5 $DOCKER_USER/$DOCKER_USER/postgres:11.5
    - docker push $DOCKER_USER/$DOCKER_USER/postgres:11.5
    - docker tag adminer $DOCKER_USER/$DOCKER_USER/adminer
    - docker push $DOCKER_USER/$DOCKER_USER/adminer:latest
    - docker tag arete $DOCKER_USER/$DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/$DOCKER_USER/arete:latest
  only:
    - master
