variables:
  DOCKER_DRIVER: overlay


stages:
  - test
  - build
  - deploy


test:
  tags:
    - dev
    - master
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  before_script:
    - whoami
  script:
    - docker-compose -f docker-compose-test.yml up
  after_script:
    - docker-compose down
  only:
    - dev
    - master


build:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
    - docker rm -vf $(docker ps -aq) &&
      docker rmi -f $(docker images -aq) &&
      docker volume prune -f
  script:
    - docker-compose up --no-start --force-recreate
  after_script:
    - docker images
    - docker container ls
  only:
    - dev
    - master


deploy:
  tags:
    - dev
    - master
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
    - docker container ls
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
    - docker-compose start
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master
