variables:
  DOCKER_DRIVER: overlay


stages:
  - test
  - build_and_deploy
  - build
  - deploy


test:
  tags:
    - dev
    - master
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  script:
    docker build -t tests -f Dockerfile-ubuntu-test .


#used for virtual environment where state is loaded in from a snapshot
build_and_deploy:
  tags:
    - dev
  image: docker:latest
  stage: build_and_deploy
  services:
    - name: docker:dind
  before_script:
    - whoami
    - docker system prune -f
    - docker-compose down -v --remove-orphans
    - docker rmi -f $DOCKER_USER/arete
    - docker images
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
    - docker-compose up -d
  after_script:
    - docker images
  only:
    - dev


build:
  tags:
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - whoami
    - docker system prune -f
    - docker-compose down -v --remove-orphans
    - docker rmi -f $DOCKER_USER/arete
    - docker images
  script:
    - docker-compose up --no-start --force-recreate
    - docker images
  only:
    - master


deploy:
  tags:
    - master
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
    - docker-compose up -d
  after_script:
    - docker container ls
  only:
    - master
