variables:
  DOCKER_DRIVER: overlay

stages:
  #  - test
  - build
  - deploy

#test:
#  tags:
#    - dev
#    - master
#  image: docker:latest
#  stage: test
#  services:
#    - name: docker:dind
#  before_script:
#    - docker system prune -af
#  script:
#    - docker-compose -f docker-compose-test.yml up --force-recreate
#  after_script:
#    - docker-compose down
#    - docker system prune -af
#  only:
#    - dev
#    - master


build:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
    - docker system prune -af
  script:
    - docker-compose -f docker-compose-build.yml up --no-start --force-recreate
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
  after_script:
    - docker-compose down
    - docker system prune -af
    - docker container ls
    - docker images
  only:
    - dev
    - master


deploy:
  tags:
    - dev
    - master
  image: $DOCKER_USER/arete:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
    - docker container ls
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker-compose -f docker-compose-deploy.yml up -d --force-recreate
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master