variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - deploy

test:
  tags:
    - docker
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  before_script:
    - apk update
    - apk upgrade
    - apt-get install curl
    - apk add python python-dev py-pip build-base
    - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose-test.yml up --force-recreate
  after_script:
    - docker-compose down
  only:
    - dev
    - master


build:
  tags:
    - docker
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - apk update
    - apk upgrade
    - apt-get install curl
    - apk add python python-dev py-pip build-base
    - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose-build.yml up --no-start --force-recreate
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
  after_script:
    - docker-compose down
  only:
    - dev
    - master


deploy:
  tags:
    - dev
    - master
  image: $DOCKER_USER/arete:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
    - docker container ls
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker-compose -f docker-compose-deploy.yml up -d --force-recreate
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master
