include:
  - template: Code-Quality.gitlab-ci.yml
code_quality:
  allow_failure: true
  artifacts:
    paths: [gl-code-quality-report.json]
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run --env SOURCE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
stages:
  - build
  - test
  - deploy


test_coverage:
  stage:
    test
  script:
    - export JAVA_HOME=/usr/lib/jvm/jdk-11.0.5+10
    - export PATH=/usr/lib/jvm/jdk-11.0.5+10/bin:$PATH
    - echo $JAVA_HOME
    - mvn --version
    - mvn install -B
    - cat target/site/jacoco/index.html


build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  script:
    - docker version
    - docker info
    - docker rm -vf $(docker ps -aq) &&
      docker rmi -f $(docker images -aq) &&
      docker volume prune -f
    - docker-compose down --rmi all -v --remove-orphans
    - docker image ls
    - docker-compose up --no-start --force-recreate
    - docker images
  only:
    - master


deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  script:
    - docker images
    - echo "$DOCKER_USER $DOCKER_PASSWD"
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker tag postgres:11.5 $DOCKER_USER/$DOCKER_USER/postgres:11.5
    - docker push $DOCKER_USER/$DOCKER_USER/postgres:11.5
    - docker tag adminer $DOCKER_USER/$DOCKER_USER/adminer
    - docker push $DOCKER_USER/$DOCKER_USER/adminer:latest
    - docker tag arete $DOCKER_USER/$DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/$DOCKER_USER/arete:latest
  only:
    - master
