variables:
  DOCKER_DRIVER: overlay

stages:
  #  - test
  - build
  - deploy


#test:
#  tags:
#    - dev
#    - master
#  image: docker:latest
#  stage: test
#  services:
#    - name: docker:dind
#  script:
#    - docker-compose -f docker-compose-test.yml up --build --force-recreate --no-deps
#  after_script:
#    - docker-compose -f docker-compose-test.yml down --remove-orphans -v -f
#  only:
#    - dev
#    - master


build:
  tags:
    - dev
    - master
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - docker container ls
    - docker images
  script:
    - docker-compose -f docker-compose-build.yml up --no-start --build --force-recreate --no-deps
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
  #    - docker push $DOCKER_USER/arete:latest
  after_script:
    - docker-compose -f docker-compose-build.yml down --remove-orphans -v -f
    - docker container ls
    - docker images
  only:
    - dev
    - master


deploy:
  tags:
    - dev
    - master
  image: $DOCKER_USER/arete:latest
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker images
    - docker container ls
    - docker-compose -f docker-compose-deploy.yml down --remove-orphans -v -f || true
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker pull automatedtestingservice/arete:latest
    - docker-compose -f docker-compose-deploy.yml up -d --force-recreate --no-deps
  after_script:
    - docker container ls
    - docker images
  only:
    - dev
    - master
