stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  script:
    - docker-compose up --no-start --force-recreate
  only:
    - master


deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  script:
    - docker images
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - docker push $DOCKER_USER/arete:latest
  only:
    - master
