variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - deploy

test:
  image: docker:latest
  stage: test
  services:
    - name: docker:dind
  script:
    docker build -t tests -f Dockerfile-ubuntu-test .


build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
  before_script:
    - whoami
    - docker system prune -f
    - docker-compose down -v --remove-orphans
    - docker rmi -f arete
    - docker images
  script:
    - docker-compose up --no-start --force-recreate
    - docker images
  only:
    - master


deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag arete $DOCKER_USER/arete:latest
    - docker push $DOCKER_USER/arete:latest
    - docker-compose up -d
  after_script:
    - docker container ls
  only:
    - master
