version: '3.4'

services:

  testing_service:
    container_name: arete
    image: arete:latest
    privileged: true
    build:
      args:
        - ARETE_HOME=/arete
      #        - GITLAB_PASSWORD=${GITLAB_PASSWORD}
      #        - DOCKER_USER=${DOCKER_USER}
      #        - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      dockerfile:
        Dockerfile-ubuntu
      context: .
    ports:
      - "8098:8098"
      - "8001:8001"
    env_file:
      - ..env #Change to .env to run locally
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ${ARETE_HOME}/input_and_output:${ARETE_HOME}/input_and_output
#      - ${ARETE_HOME}/students:${ARETE_HOME}/students
#      - ${ARETE_HOME}/tests:${ARETE_HOME}/tests
