FROM openjdk:13-jdk

MAINTAINER Agonaudid
ADD . /arete
WORKDIR /arete

RUN ls -l

ENV JAVA_OPTS=""

# Run Maven build
RUN chmod +x mvnw && ./mvnw clean install -e -X -DskipTests

# Fire up our Spring Boot app by default
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar target/arete-0.0.1-SNAPSHOT.jar" ]

EXPOSE 8098:8098
