FROM openjdk:11

MAINTAINER enrico.vompa@gmail.com

ARG ARETE_HOME
ENV ARETE_HOME=$ARETE_HOME

RUN echo $ARETE_HOME

ADD . $ARETE_HOME
WORKDIR $ARETE_HOME

ENTRYPOINT [ "sh", "-c", "chmod +x mvnw && ./mvnw test" ]

EXPOSE 8098:8098
