version: '3.4'

services:

  testing_service:
    container_name: arete
    image: ${DOCKER_USER}/arete:latest
    restart: unless-stopped
    privileged: true
    working_dir: ${ARETE_HOME}
    ports:
      - "8098:8098"
    net: "host"
    env_file:
      - ..env #Change to .env to run locally
    environment:
      ARETE_HOME: ${ARETE_HOME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ARETE_HOME}/input_and_output:${ARETE_HOME}/input_and_output
      - ${ARETE_HOME}/students:${ARETE_HOME}/students
      - ${ARETE_HOME}/tests:${ARETE_HOME}/tests
      - ${ARETE_HOME}/ssh:/root/.ssh
