version: '3.4'

services:

  db:
    container_name: postgres
    image: postgres:11.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: arete
      POSTGRES_DB: arete
      POSTGRES_PASSWORD: arete
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8090:8080"

  back:
    container_name: arete
    image: arete:latest
    restart: unless-stopped
    depends_on:
      - db
    build: .
    ports:
      - "8098:8098"
