#FROM openjdk:11
FROM ubuntu:18.04

MAINTAINER enrico.vompa@gmail.com

ARG ARETE_HOME
ENV ARETE_HOME=$ARETE_HOME

#ARG GITLAB_PASSWORD
#ENV GITLAB_PASSWORD=$GITLAB_PASSWORD
#
#ARG DOCKER_USER
#ENV DOCKER_USER=$DOCKER_USER
#
#ARG DOCKER_PASSWORD
#ENV DOCKER_PASSWORD=$DOCKER_PASSWORD

ADD . $ARETE_HOME
WORKDIR $ARETE_HOME

# Install OpenJDK-11
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Git LFS and locale
RUN apt-get install -y software-properties-common curl locales apt-utils
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install -y git-lfs
RUN git lfs install

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \ locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME
ENV JAVA_OPTS="-Dfile.encoding=UTF-8"

# Run Maven build
RUN chmod +x mvnw && ./mvnw install -DskipTests

# Run cleanup
#RUN if [ -d "/students" ]; then rm -Rf /students; fi
#RUN if [ -d "/tests" ]; then rm -Rf /tests; fi
#RUN if [ -d "/input_and_output" ]; then rm -Rf /input_and_output; fi

# Fire up our Spring Boot app by default
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /arete/target/arete-0.0.1-SNAPSHOT.jar" ]

EXPOSE 8098:8098
