version: '3.4'

services:

  db:
    container_name: postgres
    image: postgres:11.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: arete
      POSTGRES_DB: arete
      POSTGRES_PASSWORD: arete
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8090:8080"

  back:
    container_name: arete
    image: arete:latest
    restart: unless-stopped
    privileged: true
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      dockerfile:
        Dockerfile-ubuntu
      context: .
    ports:
      - "8098:8098"
    env_file:
      - .env
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AUTOMATED_TESTING_SERVER_SECRET_PASSWORD=${AUTOMATED_TESTING_SERVER_SECRET_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jar:/jar
      - output:/output


volumes:
  jar:
    driver: local
  output:
    driver: local