# VERSION 0.0.1

FROM openjdk:13

ARG uniid
ARG slug
ARG project=iti0202-2019
ARG projectBase=ex

#FROM ubuntu:latest
#
#RUN apt-get update -y && apt-get install default-jre -y

LABEL Description="New java testing container"

MAINTAINER Agonaudid

WORKDIR /

COPY jars/studenttester-core-2.0.jar JavaTester.jar
COPY students/${uniid}/${project}/${slug} student
COPY tests/${project}/${projectBase}/${slug} tester

RUN ls -l

RUN bash -c 'echo -e ${uniid}'
RUN bash -c 'echo -e ${slug}'
RUN bash -c 'echo -e ${project}'
RUN bash -c 'echo -e ${projectbase}'

#RUN java -jar JavaTester.jar -c student/ -t tester/ -jsontxt -r REPORT,CHECKSTYLE,JAR,COMPILER,TESTNG
CMD ["java", "-jar", "JavaTester.jar", "-c", "student/", "-t", "tester/", "-jsontxt", "-r", "REPORT,CHECKSTYLE,COMPILER,TESTNG"]


#java -jar tester-java/build/libs/studenttester-core-2.0.jar -c envomp/iti0202-2019/EX01IdCode/ -t iti0202-2019/ex/EX01IdCode/ -jsontxt -r REPORT,CHECKSTYLE,COMPILER,TESTNG

#docker build --build-arg uniid=envomp --build-arg slug=EX01IdCode -f Dockerfile-java-test-job -t somehash . && docker run -it somehash