FROM openjdk:13

ARG uniid
ARG slug
ARG project

LABEL Description="New java testing container"

MAINTAINER Agonaudid

WORKDIR /

COPY jars/studenttester-core-2.0.jar JavaTester.jar
COPY students/${uniid}/${project}/${slug} student
COPY tests/${project}/${slug} tester

RUN mkdir output
RUN echo '{}' > output/output.json

CMD ["java", "-jar", "JavaTester.jar", "-c", "student/", "-t", "tester/", "-jsontxt", "-r", "REPORT,CHECKSTYLE,COMPILER,TESTNG", "-o", "/output/output.json"]
